name: build

on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Get revisions
              run: make revision
            - name: Compile
              uses: xu-cheng/latex-action@v3
              with:
                root_file: resume_v2.tex
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                name: resume_v2
                path: resume_v2.pdf
